project:
  type: website
  output-dir: docs
  resources:
    -"resources/*.pdf"
  render:
    - "*.qmd"

website:
  title: "ND-HNC"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Created by Nathan Muncy via Quarto"
  sidebar:
    style: "docked"
    search: true
    logo: media/nd_logo.png
    contents:
      - text: Home
        href: index.qmd
      - text: Directions
        href: pages/directions.qmd
      - text: Compute
        href: pages/compute.qmd
      - text: Equipment
        href: pages/equipment.qmd
      - text: Facilities
        href: pages/facilities.qmd
      # - text: Forms
      #   href: pages/forms.qmd
      - text: People
        href: pages/people.qmd
      - text: Policies
        href: pages/policies.qmd
      # - text: Schedule
      #   href: pages/schedule.qmd
      - text: SOPs
        href: pages/sops.qmd
      - text: Storage
        href: pages/storage.qmd
      - text: Training
        href: pages/training.qmd
      # - text: Wiki
      #   href: pages/wiki.qmd
    tools:
      - icon: link
        href: https://neuroimaging.nd.edu
      - icon: envelope
        href: mailto:nd-hnc@nd.edu
      - icon: github
        href: https://github.com/nd-hnc

format:
  html:
    # backgroundcolor: "#D3D3D3"
    fontcolor: "#0c2340"
    linkcolor: "#ae9142"
    # mainfont: "adobe garamond premier"
    theme: [cosmo, styles.scss]

