---
title: Forms
toc: true
toc-depth: 4
---

## Overview
Documents to serve as reference, support logging, and provide operational support.

The MRI Safety Screen (Form RO01) is found [here](../resources/forms/form_RO01_mri_screen.pdf){target="_blank"}.

#### GA: Governing Articles

<!-- <details>

<summary> GA: Governing Articles</summary> -->

| Number | Title | Document | |
|-----|-----|-----|-----|
| GA01 | ACR MRI Safety | [Link](../media/articles/form_GA01_ACR_manual.pdf){target="_blank"} |
| GA02 | OHRP 2007 | [Link](../media/articles/form_GA02_OHRP_2007.pdf){target="_blank"} |
| GA03 | FDA Reports | [Link](../media/articles/form_GA03_FDA_reporting.pdf){target="_blank"} |

: {tbl-colwidths="[25,25,25,25]"}

<!-- </details> -->


#### LG: Log Issues and Maintenance
<!-- <details>

<summary> LG: Log Issues and Maintenance</summary> -->

| Number | Title | Document | |
|-----|-----|-----|-----|
| LG01 | Hardware Issue | [Link](../resources/forms/form_LG01_hardware_issue.pdf){target="_blank"} |
| LG02 | Hardware Maintenance | [Link](../resources/forms/form_LG02_hardware_maintenance.pdf){target="_blank"} |
| LG03 | Incidents | [Link](../resources/forms/form_LG03_incidents.pdf){target="_blank"} |
| LG04 | Compliance | [Link](../resources/forms/form_LG04_protocol_violations.pdf){target="_blank"} |
| LG05 | Shadow Hours | [Link](../resources/forms/form_LG05_shadow_record.pdf){target="_blank"} |
| LG06 | ACR QA | [Link](../resources/forms/form_ACR_QA.pdf){target="_blank"} |

: {tbl-colwidths="[25,25,25,25]"}

<!-- </details> -->


#### RO: Research Operations
<!-- <details>

<summary> RO: Research Operations</summary> -->

| Number | Title | Document | |
|-----|-----|-----|-----|
| RO01 | MRI Safety Screen | [Link](../resources/forms/form_RO01_mri_screen.pdf){target="_blank"} |
| RO02 | Arrival Instructions | [Blue](../resources/forms/form_RO02_arrival_blue.pdf), [White](../resources/forms/form_RO02_arrival_white.pdf){target="_blank"} |
| RO03 | ND-HNC Layout| [Link](../media/sops/nd-hnc_layout_zones.png){target="_blank"} |
| RO04 | MRI Reservation | [Link](../resources/forms/form_RO04_mri_reservation.pdf){target="_blank"} |
| RO05 | New Project | [Link](../resources/forms/form_RO05_new_project.pdf){target="_blank"} |

: {tbl-colwidths="[25,25,25,25]"}

<!-- </details> -->