---
title: Policies
toc: true
toc-depth: 2
---

## Access Levels

1. All individuals with Level 1-4 access promote a culture of safety and responsibility through actions including:
    * Reading, understanding, and seeking clarification on [SOPs](sops.qmd).
    * Ensuring access is restricted by closing doors.
    * Following policies and procedures.
    * Challenging policy and procedure non-compliance.
    * Reporting patterns of policy and procedure non-compliance.
1. Level 1 does not grant access to the Mock room (B14) or the ability to review the MRI Safety Screen.
1. Level 2 does not grant Irish1card access to Zone 3.
1. Level 3 may train to become Level 4 only for project-specific purposes.
1. A bachelor's degree is required for Level 3 access.
1. Level 4 must be accompanied by another person with at least access Level 2 when a visitor or participant is in Zone 4.
1. Only Ph.D. candidates, post-doctoral fellows, and faculty may attain Level 4 access.

## Billing

1. Form [RO04](../resources/forms/form_RO04_mri_reservation.pdf) is submitted for each MRI appointment block.
1. MRI No-shows and cancellations $<$ 24 hours before the appointment are charged at 50% scan rate.
1. "Blocked out" time slots (e.g. reserving the scanner for a full day to support a data blitz) are billed for the entire block and not only the populated appointments.

## Compliance

1. All individuals operating within the ND-HNC (researchers, staff, and faculty) are expected to read, understand, and operate in accordance with [Standard Operating Procedures](sops.qmd) and Policies.
1. Protocol violations are logged by staff in Form LG04: [Compliance](../resources/forms/form_LG04_protocol_violations.pdf){target="_blank"}.
1. A pattern of compliance issues will result in corrective actions, including access revocation.

## Compute

1. Coordinate with the ND-HNC group when utilizing a large portion of the compute resources (e.g. $>$ 400 CPUs on the HPC cluster).
    - This helps to ensure that all deadlines can be met (e.g. first-year or M.Sc. projects, revise-and-resubmit).

## Safety Screening

1. For participants with unremovable (e.g. implanted) medical devices, provide the part number and manufacturer to the MRI technologist 72 hours prior to appointment.

## Safety Zones

1. Researchers with Level access must only access Zones for which they have been authorized.
1. Researchers with Level access must wear the identifying badge while in Zones 2-4.
1. Individuals without Level access must be escorted in Zones 2-4.
1. MRI Safety Screeners must be completed by everyone entering Zone 3.
    - Researchers with Level access submit these (a) annually, and (b) whenever an event occurs that might change their MRI compatibility.

## Scheduling

1. Reservation of facilities and equipment are normally for confirmed participants.
1. Equipment/facilities are to be available for the subsequent appointment.
    - A research protocol may be interrupted by ND-HNC staff if research teams occupy equipment/facilities past their reservation.
    - A pattern of running behind schedule will result in corrective actions, including access revocation.

## Storage

1. Personal Health Information (PHI) data is __NOT__ permitted on the HPC Cluster.
1. Users or groups using a disproportionate amount of HNC resources will be required to reduce their footprint.
1. Intermediate Data can be regenerated from Original Data and should not be stored in Cold or Active Storage.
1. Data stored in Scratch should be for active analyses only.
1. Storing third-party data (e.g. HCP, NKI, ABCD) is not permitted on Cold or Active Storage.
    - Only the Final Data should be maintained.
1. Local ND-HNC compute resources (rack, workstations) are not acceptable devices for data storage.
1. Shared presentation computers (e.g. Mock and Stimulus control) should not store tasks, stimuli, or data.

## Training

1. Training (Level 1-4) must be renewed annually by attending the respective MRI Safety course and passing the exams.
    - Shadow hours do not need to be renewed.
1. Levels 2-4 must maintain current CPR/AED and First-Aid certification.
